https://habr.com/ru/articles/484214/

In [2]:
import tensorflow as tf

2024-07-22 16:51:14.255335: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-22 16:51:14.258291: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-22 16:51:14.267657: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-22 16:51:14.282784: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-22 16:51:14.286945: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-22 16:51:14.297282: I tensorflow/core/platform/cpu_feature_gu

# Разные виды тензоров

In [3]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

2024-07-22 16:51:15.975021: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [4]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

In [5]:
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]], tf.int32)

In [6]:
my_image = tf.zeros([10, 299, 299, 3])  # размер пакета x высота x ширина x количество цветовых каналов
my_image.shape

TensorShape([10, 299, 299, 3])

In [7]:
r = tf.rank(my_image)
r.numpy()

4

In [8]:
cool_numbers[1].numpy()

2.71828

In [9]:
squarish_squares[0,1].numpy()

9

In [10]:
a = tf.Variable([[1], [2]], tf.int32)
B = tf.Variable([[1, 2], [3, 4]], tf.int32)

In [11]:
B@a

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 5],
       [11]], dtype=int32)>

In [12]:
B[:, 0] # Столбец. Все нулевые элементы каждой строки

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [13]:
B[0, :] # Строка. Все элементы нулевой строки

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [14]:
B.shape, a.shape

(TensorShape([2, 2]), TensorShape([2, 1]))

# Изменение размеров tf.Tensor

In [15]:
batch_images = tf.Variable([ # Батч
    [                        # Изображение
         [[0], [3], [0]],    # Строка пикселей + 1 канал цвета
         [[2], [5], [3]],
         [[0], [2], [0]]
    ],
    [                        
         [[0], [4], [0]],    
         [[1], [7], [4]],
         [[0], [1], [0]]
    ]
], tf.int32)

In [16]:
batch_images.shape # 2 - изображения размера 3x3 с одним цветовым каналом

TensorShape([2, 3, 3, 1])

In [17]:
mlp_batch_images = tf.reshape(batch_images, [2, 3*3, 1])

In [18]:
mlp_batch_images

<tf.Tensor: shape=(2, 9, 1), dtype=int32, numpy=
array([[[0],
        [3],
        [0],
        [2],
        [5],
        [3],
        [0],
        [2],
        [0]],

       [[0],
        [4],
        [0],
        [1],
        [7],
        [4],
        [0],
        [1],
        [0]]], dtype=int32)>

# Типы данных

Тензор обязательно состоит из одного типа данных и их не так много. Но можно превратить тип данных в строку

# Вычислительный граф

In [19]:
B, a

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
 array([[1],
        [2]], dtype=int32)>)

In [20]:
a.assign([[1], [2]])

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=int32, numpy=
array([[1],
       [2]], dtype=int32)>

In [21]:
@tf.function #<---------------- Создает Хэш
def get_c():
    return tf.multiply(B, a)

In [22]:
get_c()

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [6, 8]], dtype=int32)>

In [23]:
a.assign([[2], [3]])

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=int32, numpy=
array([[2],
       [3]], dtype=int32)>

In [24]:
get_c()

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 9, 12]], dtype=int32)>

# Умножение тензора на коэффициенты

In [27]:
mlp_batch_images.shape

TensorShape([2, 9, 1])

In [25]:
w = tf.Variable(tf.random.normal([3, 9]))
w

<tf.Variable 'Variable:0' shape=(3, 9) dtype=float32, numpy=
array([[-0.37529817, -0.96892136,  0.32788092,  0.32279998, -0.10454494,
         0.77857465, -0.04577165, -1.2742859 ,  1.1864647 ],
       [ 0.432744  , -0.69004923, -0.66999274,  1.6137047 ,  2.302278  ,
        -0.39679867,  0.11999218, -1.3297992 , -0.88807976],
       [ 1.3054756 ,  0.26734534, -1.7624164 , -2.1171045 , -0.92533726,
        -0.04225465, -1.3723755 , -0.31055808, -1.8522446 ]],
      dtype=float32)>

In [31]:
data = tf.cast(mlp_batch_images, dtype=tf.float32)
tf.matmul(w, data)

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[-2.9967368],
        [ 8.818658 ],
        [-8.80674  ]],

       [[-2.4446874],
        [12.05246  ],
        [-8.004661 ]]], dtype=float32)>