https://habr.com/ru/articles/484214/

In [2]:
import tensorflow as tf

2024-07-22 11:25:15.371926: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-22 11:25:15.379557: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-22 11:25:15.454083: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-22 11:25:15.552028: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-22 11:25:15.618121: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been 

# Разные виды тензоров

In [5]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

In [6]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

In [7]:
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]], tf.int32)

In [95]:
my_image = tf.zeros([10, 299, 299, 3])  # размер пакета x высота x ширина x количество цветовых каналов
my_image.shape

TensorShape([10, 299, 299, 3])

In [15]:
r = tf.rank(my_image)
r.numpy()

4

In [20]:
cool_numbers[1].numpy()

2.71828

In [21]:
squarish_squares[0,1].numpy()

9

In [33]:
a = tf.Variable([[1], [2]], tf.int32)
B = tf.Variable([[1, 2], [3, 4]], tf.int32)

In [34]:
B@a

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 5],
       [11]], dtype=int32)>

In [36]:
B[:, 0] # Столбец. Все нулевые элементы каждой строки

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [38]:
B[0, :] # Строка. Все элементы нулевой строки

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [40]:
B.shape, a.shape

(TensorShape([2, 2]), TensorShape([2, 1]))

# Изменение размеров tf.Tensor

In [46]:
batch_images = tf.Variable([ # Батч
    [                        # Изображение
         [[0], [3], [0]],    # Строка пикселей + 1 канал цвета
         [[2], [5], [3]],
         [[0], [2], [0]]
    ],
    [                        
         [[0], [4], [0]],    
         [[1], [7], [4]],
         [[0], [1], [0]]
    ]
], tf.int32)

In [47]:
batch_images.shape # 2 - изображения размера 3x3 с одним цветовым каналом

TensorShape([2, 3, 3, 1])

In [50]:
mlp_batch_images = tf.reshape(batch_images, [2, 3*3, 1])

In [51]:
mlp_batch_images

<tf.Tensor: shape=(2, 9, 1), dtype=int32, numpy=
array([[[0],
        [3],
        [0],
        [2],
        [5],
        [3],
        [0],
        [2],
        [0]],

       [[0],
        [4],
        [0],
        [1],
        [7],
        [4],
        [0],
        [1],
        [0]]], dtype=int32)>

# Типы данных

Тензор обязательно состоит из одного типа данных и их не так много. Но можно превратить тип данных в строку

# Вычислительный граф

In [89]:
B, a

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
 array([[2],
        [3]], dtype=int32)>)

In [90]:
a.assign([[1], [2]])

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=int32, numpy=
array([[1],
       [2]], dtype=int32)>

In [91]:
@tf.function #<---------------- Создает Хэш
def get_c():
    return tf.multiply(B, a)

In [92]:
get_c()

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [6, 8]], dtype=int32)>

In [93]:
a.assign([[2], [3]])

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=int32, numpy=
array([[2],
       [3]], dtype=int32)>

In [94]:
get_c()

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 9, 12]], dtype=int32)>

# Умножение тензора на коэффициенты

TensorShape([9, 1])

In [112]:
w = tf.Variable(tf.random.normal([9, 3]))
w

<tf.Variable 'Variable:0' shape=(9, 3) dtype=float32, numpy=
array([[-0.30556992, -2.0761714 ,  0.58549786],
       [ 1.6061703 , -0.99958104, -0.99794716],
       [ 2.5366015 ,  0.7970905 , -1.8074142 ],
       [-1.4947131 ,  0.20596698,  0.3483406 ],
       [-0.65158594, -0.7994196 ,  0.39491776],
       [ 1.7868248 , -0.19231462,  0.535978  ],
       [-0.16990568, -0.5230191 , -1.1549269 ],
       [-0.6565507 , -1.4765705 ,  1.209098  ],
       [ 1.6994708 , -0.39784276,  1.2129107 ]], dtype=float32)>

In [113]:
tf.matmul(w, mlp_batch_images)

InvalidArgumentError: cannot compute _MklBatchMatMulV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:BatchMatMulV2] name: 